apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: wordpress
      hasuraService: custom
    name: wordpress
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: wordpress
      spec:
        containers:
        - image: wordpress:4
          env:
          - name: WORDPRESS_DB_HOST
            value: 'mysql.{{ cluster.metadata.namespaces.user }}'
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql.password
                name: hasura-secrets
          imagePullPolicy: IfNotPresent
          name: wordpress
          ports:
          - containerPort: 80
            protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: wordpress-data
        volumes:
        - hostPath:
            path: /data/wordpress
          name: wordpress-data
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: wordpress
      hasuraService: custom
    name: wordpress
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: wordpress
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
